export const GET_ALL_MATRIAL = "GET_ALL_MATRIAL";
export const ADD_MATRIAL = "ADD_MATRIAL"
export const DELETE_MATRIAL = "DELETE_MATRIAL"
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS"
export const GET_ALL_MATRIAL_PAGENAT = "GET_ALL_MATRIAL_PAGENAT"

export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ALL_COURSES_PAGENAT = "GET_ALL_COURSES_PAGENAT"
export const ADD_COURSE = "ADD_COURSE"
export const DELETE_COURSE = "DELETE_COURSE"
export const UPDATE_COURSE = "UPDATE_COURSE"

// Settings Actions
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE"

// Admin
export const GET_ALL_ADMINS = "GET_ALL_ADMINS"
export const ADD_ADMIN = "ADD_ADMIN"
export const DELETE_ADMIN = "DELETE_ADMIN"
export const SEND_MESSAGE = "SEND_MESSAGE"
// Error
export const GET_ERROR = "GET_ERROR"
// Auth

export const LOGIN = "LOGIN"
export const SIGN_UP = "SIGN_UP"
export const LOGOUT = "LOGOUT"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"

// Students
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_ALL_STUDENTS_PAGENAT = "GET_ALL_STUDENTS_PAGENAT"
export const ADD_STUDENT = "ADD_STUDENT"
export const DELETE_STUDENT = "DELETE_STUDENT"
export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID"

// Courses

export const GET_AVAILABLE_COURSES = "GET_AVAILABLE_COURSES"
export const GET_RECOM_COURSES = "GET_RECOM_COURSES"
export const ENROLL_SUBJECTS = "ENROLL_SUBJECTS"

// Docuemnts

export const GET_ALL_DOCS = "GET_ALL_DOCS"
export const ADD_DOC = "ADD_DOC"
export const DELETE_DOC = "DELETE_DOC"

// REsult 
export const GET_SPECIFIC_RESULT = "GET_SPECIFIC_RESULT"
export const GET_ALL_RESULTS = "GET_ALL_RESULTS"
export const UPDATE_RESULTS = "UPDATE_RESULTS"